if ! [ -x "$(command -v docker-compose)" ]; then
  echo 'Error: docker-compose is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v npm)" ]; then
  echo 'Error: npm is not installed.' >&2
  exit 1
fi

echo "
#-------------------------------------------------------
# This file was autogenerated by autoinstall.sh script
#-------------------------------------------------------

# General settings (used by any container)
UID=${UID}
GID=${UID}

# Backend/DRF env vars
BACKEND_PORT=8000

# Frontend env vars
FRONTEND_PORT=8080
BACKEND_RUNNING_ON=localhost
" > .env

cd src/frontend && npm i && cd -
docker-compose up --build
